platform :ios, '9.0'

target 'MindBlown' do
  inhibit_all_warnings!

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTAnimation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    'RCTSettings',
  ]

  pod 'Firebase/Firestore', '~> 5.15.0'
  pod 'Firebase/Auth', '~> 5.15.0'

  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'RNFirebase', path: '../node_modules/react-native-firebase/ios/RNFirebase.podspec'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'RNGoogleSignin', :path => '../node_modules/react-native-google-signin'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'RNScreens', :path => '../node_modules/react-native-screens'

  target 'MindBlownTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
