

desc 'Execute js tests'
lane :tests do
  sh 'yarn lint'
  sh 'yarn tsc'
  sh 'yarn test'

  if Helper.is_ci?
    build_ios
    build_android
  end
end

before_all do
  skip_docs
  sh 'yarn install'
end

desc 'Build iOS app'
lane :build_ios do
  sh 'yarn install-ios'

  build_ios_app(
    export_method: 'development',
    workspace: 'ios/MindBlown.xcworkspace',
    scheme: 'MindBlown',
    configuration: 'Debug',
    skip_package_ipa: true,
    skip_archive: true,
    destination: 'platform=iOS Simulator,name=iPhone 8,OS=12.1'
  )

  # setup certificates
  # setup build
end

desc 'Build Android app'
lane :build_android do
  gradle(task: 'clean', project_dir: 'android/')
  gradle(task: 'assemble', build_type: 'Debug', project_dir: 'android/')

  move_to_deploy()
end

desc 'Release Android app'
lane :release_android do
  gradle(task: 'clean', project_dir: 'android/')
  gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')

  move_to_deploy()
end

def move_to_deploy()
  apk_location = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
  out_dir = ENV['BITRISE_DEPLOY_DIR'] || '../build/'

  UI.message "Moving bundle to \"#{out_dir}\""
  sh "cp #{apk_location} #{out_dir}"
end
