

desc 'Execute js tests'
lane :tests do
  sh 'yarn lint'
  sh 'yarn tsc'
  sh 'yarn test'
end

before_all do
  skip_docs
  sh 'yarn install'
end

desc 'Build Dev apps'
lane :build_dev do
  build_ios_dev
  build_android_dev
end

desc 'Build iOS Dev app'
lane :build_ios_dev do
  sh 'yarn install-ios'

  build_ios_app(
    export_method: 'development',
    workspace: 'ios/MindBlown.xcworkspace',
    scheme: 'MindBlown',
    configuration: 'Debug',
    skip_package_ipa: true,
    skip_archive: true,
    destination: 'platform=iOS Simulator,name=iPhone 8,OS=12.0'
  )

  # setup certificates
  # setup build
end

desc 'Build Android Dev app'
lane :build_android_dev do
  gradle(task: 'clean', project_dir: 'android/')
  gradle(task: 'assemble', build_type: 'Debug', project_dir: 'android/')

  cp_to_deploy()
end

desc 'Build Android Release app'
lane :build_android_release do
  gradle(task: 'clean', project_dir: 'android/')
  gradle(task: 'assemble', build_type: 'Release', project_dir: 'android/')

  cp_to_deploy()
end

desc 'Release Android app'
lane :release_android do
  build_android_release

  upload_to_play_store(
    package_name: 'com.shufflow.MindBlown',
    track: 'internal',
    json_key: 'google_play_key.json',
    apk: lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH],
  )
end

def cp_to_deploy()
  apk_location = "#{lane_context[SharedValues::GRADLE_APK_OUTPUT_PATH]}"
  out_dir = ENV['BITRISE_DEPLOY_DIR'] || '../build/'

  UI.message "Moving bundle to \"#{out_dir}\""
  sh "cp #{apk_location} #{out_dir}"
end
