const fonts = [
  'Copperplate',
  'Heiti SC',
  'Apple SD Gothic Neo',
  'Thonburi',
  'Gill Sans',
  'Marker Felt',
  'Hiragino Maru Gothic ProN',
  'Courier New',
  'Kohinoor Telugu',
  'Heiti TC',
  'Tamil Sangam MN',
  'Helvetica Neue',
  'Gurmukhi MN',
  'Georgia',
  'Times New Roman',
  'Sinhala Sangam MN',
  'Arial Rounded MT Bold',
  'Kailasa',
  'Kohinoor Devanagari',
  'Kohinoor Bangla',
  'Chalkboard SE',
  'Apple Color Emoji',
  'PingFang TC',
  'Gujarati Sangam MN',
  'Geeza Pro',
  'Damascus',
  'Noteworthy',
  'Avenir',
  'Mishafi',
  'Academy Engraved LET',
  'Futura',
  'Party LET',
  'Kannada Sangam MN',
  'Arial Hebrew',
  'Arial',
  'Chalkduster',
  'Kefa',
  'Hoefler Text',
  'Optima',
  'Palatino',
  'Malayalam Sangam MN',
  'Al Nile',
  'Lao Sangam MN',
  'Bradley Hand',
  'Hiragino Mincho ProN',
  'PingFang HK',
  'Helvetica',
  'Courier',
  'Cochin',
  'Trebuchet MS',
  'Devanagari Sangam MN',
  'Oriya Sangam MN',
  'Rockwell',
  'Snell Roundhand',
  'Zapf Dingbats',
  'Bodoni 72',
  'Verdana',
  'American Typewriter',
  'Avenir Next',
  'Baskerville',
  'Khmer Sangam MN',
  'Didot',
  'Savoye LET',
  'Symbol',
  'Charter',
  'Menlo',
  'Noto Nastaliq Urdu',
  'Bodoni 72 Smallcaps',
  'DIN Alternate',
  'Papyrus',
  'Hiragino Sans',
  'PingFang SC',
  'Myanmar Sangam MN',
  'Zapfino',
  'Telugu Sangam MN',
  'Bodoni 72 Oldstyle',
  'Euphemia UCAS',
  'Bangla Sangam MN',
];

export default fonts;
